name: Build 2 EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-client:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install
        run: |
          pip install PyQt5
          pip install requests
          pip install pyinstaller

      - name: Build Client
        working-directory: ./client
        run: >
          pyinstaller --onefile --windowed
          --name RRSTrainer-Client
          --add-data "data;data"
          --add-data "images;images"
          --icon icon.ico
          main.py

      - uses: actions/upload-artifact@v4
        with:
          name: RRSTrainer-Client
          path: client/dist/RRSTrainer-Client.exe

  build-server:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install
        run: |
          pip install PyQt5
          pip install Flask
          pip install pyinstaller

      - name: Build Server
        working-directory: ./server
        run: >
          pyinstaller --onefile --windowed
          --name RRSTrainer-Server
          --paths "logic"
          --paths "ui"
          --paths "../shared"
          --hidden-import api
          --hidden-import database
          --hidden-import broadcast
          --hidden-import main_window
          --hidden-import config
          --add-data "../shared;shared"
          --add-data "../client/data;data"
          main.py

      - uses: actions/upload-artifact@v4
        with:
          name: RRSTrainer-Server
          path: server/dist/RRSTrainer-Server.exe
